---
title: "Proyecto - Contingencias de Vida II"
author: 
  - Luis Fernando Amey Apuy - C20470
  - Javier Hernández Navarro - C13674
  - Anthony Mauricio Jiménez Navarro - C24067
  - Gustavo Alberto Amador Fonseca - C20459
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    self_contained: true
    highlight: tango
---
# Librerías
```{r}
source("cod/setup.R")
```

# Lectura de la base de datos
```{r, warning=FALSE, message=FALSE}
source("cod/load_database.R")
```

```{r}
source("cod/prob_estim.R")
prob_estim(1, 20, 0, 1)
```
```{r}
red_factor_mort(20,60,1)
```
```{r}
red_factor_rest <- function(x, t, sex, series){
  # Mejora las mortalidades con respecto al tiempo
  k <- 0.3
  if(series == 1){
    c <- 0.625
    h <- 0.106
  } else if(series == 2){
    c <- 0.6
    h <- 0.197
  } else {
    c <- 0.566
    h <- 0.272
  }
  if(x > 65){
    alpha <- 1 + (1-c)*(x-120)/65
    f <- ((120-x)*h + (x-65)*k)/65
  } else {
    alpha <- c
    f <- h
  }
  return(alpha + (1-alpha)*(1-f)^(t/20))
}
```

```{r}
red_factor_rest(65, 53, 1, 1)
```

```{r}
prob <- function(x, n){
  return((table_males$`q_{x}`[x+1]) + add_mortality(x,n))
}
```
# Empezar las tablas

## Profound
```{r}
Profound <- data.frame(x = 0:119, Severe = 0.05, Profound = 0, Dead = 0)
Profound$Dead[1:110] <- sapply(0:109, function(x) prob(x,4))
Profound$Severe[110:120] <- seq(0.05,0,length.out = 11)
Profound$Dead[120] <- 1
interpol <- smooth.spline(c(Profound$x[100:110], 120), c(Profound$Dead[100:110], 1))
Profound$Dead[110:119] <- predict(interpol, 110:119)$y
Profound$Profound <- 1 - Profound$Severe - Profound$Dead
```

## Severe
```{r}
Severe <- data.frame(x = 0:119, Moderate = 0.1, Severe = 0, Profound = 0, Dead = 0)
Severe$Dead[1:110] <- sapply(0:109,function(x) (table_males$`q_{x}`[x+1]) + add_mortality(x,3))
Severe$Dead[120] <- 1
interpol <- smooth.spline(c(Severe$x[100:110], 120), c(Severe$Dead[100:110], 1))
Severe$Dead[110:119] <- predict(interpol, 110:119)$y

Severe$Moderate[110:120] <- seq(0.1,0,length.out = 11)
# Profound$Profound <- 1 - Profound$Severe - Profound$Dead
```











